apiVersion: v1
kind: Service
metadata:
  name: caresync-gateway-nodeport
  namespace: {{ .Values.global.namespace }}
  labels:
    app: caresync-gateway-nodeport
spec:
  type: NodePort
  selector:
    gateway.networking.k8s.io/gateway-name: caresync-gateway
  ports:
    - port: 80
      targetPort: 80
      nodePort: {{ .Values.gateway.nodePort }}
      protocol: TCP
