apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Release.Name }}
type: Opaque
stringData:
  mongoRootUsername: "admin"
  mongoRootPassword: "admin123"
