
# ArgoCD Manifest — values.yaml
# Repository : caresync-org/argoCD-manifests
# Branch     : dev
#
# This file is automatically updated by the CI/CD pipeline (Job 5 — CD).
# ArgoCD watches this repo and syncs to the cluster on every commit.


global:
  registry: docker.io
  organization: nandana2002
  pullPolicy: IfNotPresent
  namespace: caresync-dev

auth:
  enabled: true
  replicaCount: 1
  image:
    repository: caresync-auth
    tag: dev-0000000
  service:
    port: 4001
  env:
    NODE_ENV: development
    MONGO_URI: "mongodb://auth-mongodb:27017/auth"
    JWT_SECRET: "change-me-in-production"
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "300m"
      memory: "256Mi"

patient:
  enabled: true
  replicaCount: 1
  image:
    repository: caresync-patient
    tag: dev-0000000
  service:
    port: 4002
  env:
    NODE_ENV: development
    MONGO_URI: "mongodb://patient-mongodb:27017/patient"
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "300m"
      memory: "256Mi"

doctor:
  enabled: true
  replicaCount: 1
  image:
    repository: caresync-doctor
    tag: dev-0000000
  service:
    port: 4003
  env:
    NODE_ENV: development
    MONGO_URI: "mongodb://doctor-mongodb:27017/doctor"
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "300m"
      memory: "256Mi"

appointment:
  enabled: true
  replicaCount: 1
  image:
    repository: caresync-appointment
    tag: dev-0000000
  service:
    port: 4004
  env:
    NODE_ENV: development
    MONGO_URI: "mongodb://appointment-mongodb:27017/appointment"
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "300m"
      memory: "256Mi"

frontend:
  enabled: true
  replicaCount: 1
  image:
    repository: caresync-frontend
    tag: dev-0000000
  service:
    type: ClusterIP
    port: 3000
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "300m"
      memory: "512Mi"

mongodb:
  image:
    repository: mongo
    tag: "7.0"
  replicas: 1
  persistence:
    enabled: true
    storageClass: nfs-storage
    accessMode: ReadWriteMany
    size: 2Gi

gateway:
  className: kgateway
  port: 80
  protocol: HTTP
  nodePort: 30080

instanceDatabase: ""
instancePairedService: ""
