apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: appointment-mongodb-dev
  namespace: argocd
  labels:
    environment: dev
    service: appointment-mongodb
spec:
  project: caresync
  source:
    repoURL: https://github.com/caresync-org/argoCD-manifests
    targetRevision: dev
    path: charts/mongodb
    helm:
      releaseName: appointment-mongodb
      valueFiles:
        - ../../values.yaml
      parameters:
        - name: instanceDatabase
          value: appointment
        - name: instancePairedService
          value: appointment-service
        - name: global.namespace
          value: caresync-dev
  destination:
    server: https://kubernetes.default.svc
    namespace: caresync-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
