apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: appointment-service-dev
  namespace: argocd
  labels:
    environment: dev
    service: appointment-service
spec:
  project: caresync
  source:
    repoURL: https://github.com/caresync-org/argoCD-manifests
    targetRevision: dev
    path: charts/appointment-service
    helm:
      valueFiles:
        - ../../values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: caresync-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
