apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: appointment-service-prod
  namespace: argocd
  labels:
    environment: prod
    service: appointment-service
spec:
  project: caresync
  source:
    repoURL: https://github.com/caresync-org/argoCD-manifests
    targetRevision: production
    path: charts/appointment-service
    helm:
      valueFiles:
        - ../../values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: caresync-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
