apiVersion: v1
kind: ConfigMap
metadata:
  name: appointment-service-config
  namespace: {{ .Values.global.namespace }}
  labels:
    app: appointment-service
data:
  NODE_ENV: {{ .Values.appointment.env.NODE_ENV | quote }}
  PORT: {{ .Values.appointment.service.port | quote }}
