apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-appointment-service
  namespace: {{ .Values.global.namespace }}
spec:
  podSelector:
    matchLabels:
      app: appointment-service
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: kgateway
      ports:
        - protocol: TCP
          port: {{ .Values.appointment.service.port }}
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: appointment-mongodb
      ports:
        - protocol: TCP
          port: 27017
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
