apiVersion: v1
kind: Secret
metadata:
  name: appointment-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    app: appointment-service
type: Opaque
stringData:
  mongoUri: {{ .Values.appointment.env.MONGO_URI | quote }}
