apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    app: auth-service
type: Opaque
stringData:
  mongoUri: {{ .Values.auth.env.MONGO_URI | quote }}
  jwtSecret: "caresync-jwt-secret"
