apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: caresync
  namespace: argocd
spec:
  description: CareSync Appointment Booking Platform
  sourceRepos:
    - https://github.com/caresync-org/argoCD-manifests
  destinations:
    - namespace: caresync-dev
      server: https://kubernetes.default.svc
    - namespace: caresync-prod
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
