apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctor-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app: doctor-service
spec:
  replicas: {{ .Values.doctor.replicaCount }}
  selector:
    matchLabels:
      app: doctor-service
  template:
    metadata:
      labels:
        app: doctor-service
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: doctor-service
          image: "{{ .Values.global.organization }}/{{ .Values.doctor.image.repository }}:{{ .Values.doctor.image.tag }}"
          imagePullPolicy: {{ .Values.global.pullPolicy }}
          ports:
            - containerPort: {{ .Values.doctor.service.port }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
          envFrom:
            - configMapRef:
                name: doctor-service-config
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: doctor-secret
                  key: mongoUri
          resources:
            requests:
              cpu: {{ .Values.doctor.resources.requests.cpu }}
              memory: {{ .Values.doctor.resources.requests.memory }}
            limits:
              cpu: {{ .Values.doctor.resources.limits.cpu }}
              memory: {{ .Values.doctor.resources.limits.memory }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.doctor.service.port }}
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.doctor.service.port }}
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
