apiVersion: v1
kind: Secret
metadata:
  name: doctor-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    app: doctor-service
type: Opaque
stringData:
  mongoUri: {{ .Values.doctor.env.MONGO_URI | quote }}
