apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: {{ .Values.global.namespace }}
  labels:
    app: frontend
data:
  NODE_ENV: "production"
  PORT: {{ .Values.frontend.service.port | quote }}
