apiVersion: v1
kind: ConfigMap
metadata:
  name: patient-service-config
  namespace: {{ .Values.global.namespace }}
  labels:
    app: patient-service
data:
  NODE_ENV: {{ .Values.patient.env.NODE_ENV | quote }}
  PORT: {{ .Values.patient.service.port | quote }}
