apiVersion: v1
kind: Secret
metadata:
  name: patient-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    app: patient-service
type: Opaque
stringData:
  mongoUri: {{ .Values.patient.env.MONGO_URI | quote }}
