apiVersion: v1
kind: Service
metadata:
  name: patient-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app: patient-service
spec:
  type: ClusterIP
  selector:
    app: patient-service
  ports:
    - port: {{ .Values.patient.service.port }}
      targetPort: {{ .Values.patient.service.port }}
      protocol: TCP
