{{- if and .Values.secrets.useSealedSecrets (eq .Values.global.environment "production") }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: caresync-secrets
  namespace: {{ .Values.global.namespace }}
spec:
  encryptedData:
    JWT_SECRET: AgADnACSz6ftXBBKC1OveV1Hle/WlwhQQ/t4AyWnpk5q9HavEryFCL/gDQOpPg8KCzQzke5joktocd5D1e7seJfEmHDro/DWzwwGPKplkeV5NbJBra0lYh7pQlvHXV2W6NS8GA3wQhpD09IYeNXFXq5nZ5myWTGshrAW928W59LDp7OxOabnn0uMDWN6Ic/icYvVZxgOgQfTZK+8rj/W6HZX/g8vvUk+1wwMcl+kpE7N2OLZqh2SJ0ofxaCjHN3jf//KapIZCcLmDKTKnbv3LtqpJbJu1WJGq4zP5pUte9EPakQ8YVP8PY+WP5npDpOBSwlI7gBlm/NOx2cLxHGk8mxvIcZYiT/IUmed/fLWeZBiHCtHOvBXNoD+nqxC7JDMpzaqQQBjvLRdcMZGalNCl/5nZlUDHWaltBf0Eha1Nd6UlnzjEVm1tr6nuCdMZjdr7Sg4rZRjgP+UCREI2z2tbCo/YtY5lYJvPW8p4XHWLkOPuKaVLJzUuCXNNKeQoSp4+gxIipmUd9Q5p3tUJPz/Xq78aIb7AoQyUXntof8XGjQ59OhlPMqXTruH7Adi9RWXiAzaCpSBRrlg63XRa40Ll8pxfYJDLvLHfPQin+kZfkRC48X4kBTj1tQ1T6uJCkvz8t+p0ysLh1ef7KSyxOqNLUAQTzamXX+TejU2thEpfraabGKpXVvV31Kmw3lrtvbhhThP5brrJb03PvxVZcaRHSTxVHnrcfK77Eb0w1scxA==
  template:
    metadata:
      creationTimestamp: null
      name: caresync-secrets
      namespace: {{ .Values.global.namespace }}
{{- end }}
