{{- if and .Values.secrets.useSealedSecrets (eq .Values.global.environment "production") }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: caresync-secrets
  namespace: {{ .Values.global.namespace }}
spec:
  encryptedData:
    JWT_SECRET: AgDIfA8g2RmvYsluAvmLe0p+vHcrKG/1UB8hjR0/Xodrg6RmCNdzGP52apktrJEXm5gduuN0svNxav/Y4zFovYGXFiVfr0h5zN5g/th0bnFckj0SFk7Nbz9yQs5x/0OAHwf81HR+ccswPLmU4xMH6V8S3st+Ejo0urbY22if1g9fNq3x9JaUlNLnk+w35PmO5dUIjYnnpSNCzRcHG7CZZuK1YrbucTaFVJTeYEPkglqE6m5pmnuULibxTrIh8C86d3oQu80UHJm45UPk0qLha6P6Cf3YkdjVAY3nQtRz4AyGqls0jwtaLk6BBwGgg3LZ7wlTkLov3qgXL3MCbSiNo+gGQO8eSmwQW1whMpYZ2aKGzRKhcwE5iw2nkTW4MBItUbrEZIv8v2JRj1O908wWD0tLYhmlq51m6Vf2jmJzWmB3tA5trrzI8lsFzOw9Z+bvf519MlNZCqJQ1JVE3XmbcakNiV7exekgOsFycrpMuk8hjZ00B+RjetuUDgrvUxWF9pDBzv8MWmzNEmD49mtj7WH7BqOqTB/+5l8JGAl9Zo79SdaN7MdQX7DEbVd2G+Q5ODL54Fk8wg78cA55qJEyysPrwzqqbgHPtKuOOJJDeyBPrtWjI2TL+4Jl0GdI1+q6uW/hjONAtfWwVr4qM2BkP6e6tYEiTwsGgaMh3XnD1W6QlyQCpSVZLjvjArF+LVTDzyA9PAqNpDJ/S1pzyvWHa1GqpY7PPeTw0/VXoXTpPg==
  template:
    metadata:
      creationTimestamp: null
      name: caresync-secrets
      namespace: {{ .Values.global.namespace }}
{{- end }}
