{{- if and .Values.secrets.useSealedSecrets (eq .Values.global.environment "development") }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: caresync-secrets
  namespace: {{ .Values.global.namespace }}
spec:
  encryptedData:
    JWT_SECRET: AgBQ1d+GFig0PbfTmOEcmLHamNP1oqc5Vyf1BdK7Y8kMH25ga1+j6VjlSfTjeobUR+SXZt+c43XsjQFswAtOVJE+Rh9/COVC8sRX865ahTEMFh0seIruBoHvL21LY6ETM8gwj1D3brqA/LyvidI8+MDIY/nqi11r29PdshXkgkEdDuzSilXYhw3TEA3isQVtRYsqYv+Bu+H6JMhKxFvi9/LdIrTzUKzJmtMe7HIqwA8cWD1g70EMm9GFDg0i3AlyJw68MFUe1DvTjAoYXF/s/IwYN7PYEEX+bHdJA2z13R+MuAYhVNl/DBMD8eicmBzJPnVnmxx0yqlkHqxdoHLm4UNLcHJUr00HAWr0aWzE+B9kiM3qoJ0Jrtl7q+z5wTEkL3ArbOznCxTvhUVwMO0NWP7C4lAuXNoVdllhsnCcWo8Fl2XfIUkcyKb/OvKtfTOiX03lLhNSSLmP9CStCtqVjHc/+kRIHannPyqBla68UWuJ+/dPrRzscGJhmQbdSvgiA2wNxTF4qvI/6pFwUrwsLqxYNlw0v/VUK/yYBFmNJ+9pOs7LYQDx2yv68lShkp0RtaQyvlH7jpce7cRqsqGTrrpn1g50u0FNnKUwsIK45FzhjYakYzNfsh1Fuoan/sQJMFHmzRcKyIOrZrSqk6WDPeEDUDM8I9WiCqED9UvStJ8nHNGGACXfz7zPYUI8cqCgfZcTsJWby4OFJ1vnv2nue4vgDxaPaxuxO18ITh5M
  template:
    metadata:
      creationTimestamp: null
      name: caresync-secrets
      namespace: {{ .Values.global.namespace }}
{{- end }}
