{{- if and .Values.secrets.create (not .Values.secrets.useSealedSecrets) }}
apiVersion: v1
kind: Secret
metadata:
  name: caresync-secrets
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.secrets.jwtSecret }}
{{- end }}
